server.port=8080
spring.application.name=bff-gateway

ms.usuarios.url=http://localhost:8081
ms.donaciones.url=http://localhost:8082
ms.necesidades.url=http://localhost:8083

resilience4j.circuitbreaker.instances.ms-usuarios.slidingWindowSize=5
resilience4j.circuitbreaker.instances.ms-usuarios.failureRateThreshold=50
resilience4j.circuitbreaker.instances.ms-usuarios.waitDurationInOpenState=10s

resilience4j.circuitbreaker.instances.ms-donaciones.slidingWindowSize=5
resilience4j.circuitbreaker.instances.ms-donaciones.failureRateThreshold=50
resilience4j.circuitbreaker.instances.ms-donaciones.waitDurationInOpenState=10s

resilience4j.circuitbreaker.instances.ms-necesidades.slidingWindowSize=5
resilience4j.circuitbreaker.instances.ms-necesidades.failureRateThreshold=50
<<<<<<< HEAD
resilience4j.circuitbreaker.instances.ms-necesidades.waitDurationInOpenState=10s
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=TRACE
=======
resilience4j.circuitbreaker.instances.ms-necesidades.waitDurationInOpenState=10s
>>>>>>> b72499bb6489d2c1f2568c89e7f2bd8660ad7b6f
